apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name  }}
spec:
  selector:
    app: {{ .Values.service.spec.selector.app  }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
